# default libary is @envtio/base
type: container # ContainerBeacon (namespace: compute ~ future view aggregation)
name: site

props:
  cluster: network-v1/fargate-cluster
  image: ${{ env:image }}
  port: 8080
  desired: 2
  cpu: 256
  memory: 512
  target:
    edge: api
    rules:
      - path: /
        priority: 100

resources:
  - name: events
    type: queue # QueueBeacon (namespace: compute)
    props:
      is_fifo: true
      subscription: events
  - name: db
    type: database # DatabaseBeacon (namespace: compute)
    props:
      cluster: pg-cluster

access:
  inbound:
    - api
  outbound:
    - import-api
